export const discourseEN = [
    "Now, it is very, very important to solve the problem of the subject. So, ",
    "We have to face a very embarrassing fact, that is, ",
    "The occurrence of the subject, how exactly need to be achieved, and how will it occur if the subject does not occur. ",
    "And these are not entirely important, the more important question is, ",
    "The subject, how to achieve it. ",
    "With these questions, let's examine the subject. ",
    "The so-called subject, the key is how the subject needs to be written. ",
    "We generally believe that if we grasp the key to the problem, everything else will be solved. ",
    "What is the crux of the problem? ",
    "Why did the subject happen? ",
    "Everyone has to face these problems.  When facing such problems, ",
    "Generally speaking, we must all consider carefully. ",
    "Think clearly about the subject, what kind of existence is it. ",
    "Understanding clearly what kind of existence the subject is is the key to solving all problems. ",
    "As far as I am concerned, the meaning of the subject to me is very important. ",
    "I also think deeply about this issue every day and night. ",
    "The subject, what will happen if it happens, what will happen if it doesn't happen. ",
    "Under such a difficult choice, I think about it, and I have trouble sleeping and eating. ",
    "In life, if the subject appears, we have to consider the fact that it appears. ",
    "This fact is of great significance to me, and I believe it also has a certain meaning to the world. ",
    "We all know that as long as it makes sense, it must be carefully considered. ",
    "In that case, ",
    "So, ",
    "I think, ",
    "Generally speaking, ",
    "In summary, ",
    "Well, ",
    "After the above discussion",
]

export const famousQuotesEN = [
    "Voltaire once said that there can be no great career without great difficulties. This makes me think deeply",
    "Fuller once said that suffering tempers some people and destroys others. This makes me think deeply",
    "Vincent Peel once said that by changing your mind, you will change your own world. This makes me think deeply",
    "Napoleon Hill once said, don't wait, the timing will never be just right. This makes me think deeply",
    "Seneca once said that life is like a fable. Its value is not in its length, but in its content. This makes me think deeply",
    "Oprah Winfrey once said that what you believe is what you become. This makes me think deeply",
    "Lucette once said that there can be no two in life, but many people are not good at spending it even once. This makes me think deeply",
    "Shakespeare once said that a person's life is short, but if you live this life despicably, it will be too long. This makes me think deeply",
    "Descartes once said that my hard work in studying did not get any other benefits, but I became more and more aware of my ignorance. This makes me think deeply",
    "Zola once said that once the path of life is chosen, one must bravely walk to the end and never look back. This makes me think deeply",
    "Michele Pan once said that life is a treacherous gorge that only the brave can pass. This makes me think deeply",
    "Jim Ron once said that either you are in charge of life or you are in charge of life. This makes me think deeply",
    "A Japanese proverb once said that misfortune may become a bridge to happiness. This makes me think deeply",
    "Haibel once said that life is a school. There, it is better to say that a good teacher is misfortune than a good teacher is happiness. This makes me think deeply",
    "Generell George S. Patton once said that if you accept a challenge, you can enjoy the joy of victory. This makes me think deeply",
    "Democritus once said that temperance increases happiness and strengthens enjoyment. This makes me think deeply",
    "Pestalozzi once said that I did not do what I should do today, and I will be delayed tomorrow morning. This makes me think deeply",
    "Goethe once said that what determines a person's life and the entire destiny is only a moment. This makes me think deeply",
    "Carnegie once said that a person who does not pay attention to small things will never achieve a big cause. This makes me think deeply",
    "Rousseau once said that wasting time is a big sin. This makes me think deeply",
    "Kant once said that since I have embarked on this path, nothing should hinder me from going down this path. This makes me think deeply",
    "Sir Klaus Mercer once said that education costs money, and ignorance is the same. This makes me think deeply",
    "Voltaire once said that upholding a great cause of will requires unswerving spirit. This makes me think deeply",
    "Abraham Lincoln once said that it doesn't matter how many years you live, what matters is how you spent these years. This makes me think deeply",
    "Han Fei once said that internally and externally, words and deeds are commensurate. This makes me think deeply",
    "Franklin once said, do you love life? Then don't waste time, because time is the material of life. This makes me think deeply",
    "Malton once said that strong confidence can make ordinary people do amazing careers. This makes me think deeply",
    "Descartes once said that to read all good books is to talk to many noble people. This makes me think deeply",
    "Seneca once said that real life can only be achieved after a difficult struggle. This makes me think deeply",
    "Ibsen once said that a great cause requires determination, ability, organization and responsibility. This makes me think deeply",
    "Goethe once said that no one knows in advance how powerful he is, until he tries it. This makes me think deeply",
    "Darwin once said that a person who dared to waste even an hour's time shows that he still does not know how to cherish the full value of life. This makes me think deeply",
    "Anonymous once said, be grateful for every new challenge, because it will forge your will and character. This makes me think deeply",
    "Ostrowski once said that a common cause, a common struggle, can give people the power to endure everything. This makes me think deeply",
    "Su Shi once said that those who set great things in ancient times are not only talents who are beyond the world, but also have the will to persevere. This makes me think deeply",
    "Wang Yangming once said, so those who are determined have the heart to learn; for scholars, they are also determined. This makes me think deeply",
    "Goethe once said that reading a good book is like talking to a noble person. This makes me think deeply",
    "Ushinsky once said that learning is labor, a labor full of thought. This makes me think deeply",
    "Belinsky once said that good books are the most precious treasures. This makes me think deeply",
    "Franklin once said that reading is easy and thinking is difficult, but without one of the two, it's useless. This makes me think deeply",
    "Rubakin once said that reading is to build up my own thoughts with the help of other people's thoughts. This makes me think deeply",
    "Bacon once said that arranging time reasonably is equivalent to saving time. This makes me think deeply",
    "Turgenev once said, do you want to be a happy person? I hope you learn to bear hardship first. This makes me think deeply",
    "Shakespeare once said that the person who abandons time, time also abandons him. This makes me think deeply",
    "Schopenhauer once said that ordinary people only think of how to spend time, and talented people try to use time. This makes me think deeply",
    "Bo once said that a failure only proves that our determination to succeed is strong enough. This makes me think deeply",
    "La Roshvko once said that perseverance when achieving success is more important than being tenacious when failing. This makes me think deeply",
    "Shakespeare once said that a person's life is short, but if you live this life despicably, it will be too long. This makes me think deeply",
    "Bismarck once said that failure is the last test of perseverance. This makes me think deeply",
    "Daisaku Ikeda once said, don't avoid distress and difficulties, stand up to challenge it, and then overcome it. This makes me think deeply",
    "Shakespeare once said that the wisdom in that head is like sparks in the flint and steel. If you don't hit it, you won't come out. This makes me think deeply",
    "Greece once said that the most difficult thing is to know yourself. This makes me think deeply",
    "Hesse once said that he is a hero who has the courage to take on his destiny. This makes me think deeply",
    "Africa once said that even the most agile people can't see their backs. This makes me think deeply",
    "Bacon once said that reading makes people fulfilling, meeting makes people quick, and writing makes people precise. This makes me think deeply",
    "Spinoza once said that the greatest pride over the greatest inferiority complex is the weakest of the soul. This makes me think deeply",
    "Spain once said that self-knowledge is the most rare knowledge. This makes me think deeply",
    "Seneca once said that courage leads to heaven, and cowardice leads to hell. This makes me think deeply",
    "Helps once said that sometimes reading is a way to cleverly avoid thinking. This makes me think deeply",
    "Descartes once said that reading all good books is like talking to the most outstanding person in the past. This makes me think deeply",
    "Deng Tuo once said that the more incompetent the more pretentious. This makes me think deeply",
    "Ireland once said that the more incompetent people are, the more they like to pick other people's mistakes. This makes me think deeply",
    "Lao Tzu once said that knowing others is wise, knowing one is clear. Those who overcome others are powerful, and those who overcome themselves are strong. This makes me think deeply",
    "Goethe once said that a strong-willed person can put the world in his hands and knead it like mud. This makes me think deeply",
    "Michael F. Staley once said that the most challenging challenge is to improve myself. This makes me think deeply",
    "Edison once said that failure is what I need, and it is as valuable to me as success. This makes me think deeply",
    "Russell Baker once said that even if a person has reached the top, he still has to strive for self-improvement. This makes me think deeply",
    "Ma Yun once said that the biggest challenge and breakthrough lies in employing people, and the biggest breakthrough in employing people lies in trusting people. This makes me think deeply",
    "Lei Feng once said that I live to make others' lives better. This makes me think deeply",
    "Bulvo once said that to master books, don't be mastered by books; read for a living, don't live for reading. This makes me think deeply",
    "Bacon once said that if you know that praise of good things is too exaggerated, it will also attract people's resentment, contempt and jealousy. This makes me think deeply",
    "Mozart once said that whoever works as hard as me will be as successful as me. This makes me think deeply",
    "Marx once said that all savings, in the final analysis, boil down to time savings. This makes me think deeply",
    "Shakespeare once said that will and destiny often go against each other, and determination will be overthrown in the end. This makes me think deeply",
    "Carlisle once said that the essence of all past times is in the book. This makes me think deeply",
    "Bacon once said, peep into your own heart, and then realize that all the miracles are in you. This makes me think deeply",
    "Romain Roland once said that only by turning the feeling of complaining about the environment into a motivated force is the guarantee of success. This makes me think deeply",
    "Confucius once said that those who know are not as good as those who know, and those who are good are not as good as those who enjoy. This makes me think deeply",
    "Da Vinci once said that bold and firm determination can be worthy of a weapon's sophistication. This makes me think deeply",
    "Schopenhauer once said that the will is a strong blind man, leaning on the shoulders of a lame man with a clear eye. This makes me think deeply",
    "Hegel once said that only people who lie in the mud forever will not fall into the pit again. This makes me think deeply",
    "Premchand once said that once the lamp of hope goes out, life turns into darkness in an instant. This makes me think deeply",
    "Weilong once said that you don't need any special talents to succeed, just do the small things you can do well. This makes me think deeply",
    "Guo Moruo once said that the decisive factor in the formation of genius should be diligence. This makes me think deeply",
    "Locke once said that the trick to learning a lot of things is not to learn a lot at once. This makes me think deeply",
    "Spain once said that their shoes, they know where they are tight. This makes me think deeply",
    "La Roche Foucault once said that the only shortcoming we will not correct is weakness. This makes me think deeply",
    "Abraham Lincoln once said that I am a person who walks slowly, but I never go back. This makes me think deeply",
    "Military Warner once said, don't ask what the secret of success is, and do your best to do what you should do. This makes me think deeply",
    "Bismarck once said that there is no such thing as failure for an indomitable person. This makes me think deeply",
    "Abu Ri Faraz once said that learning is an extremely precious thing, and it is not shameful to absorb it from any source. This makes me think deeply",
    "Bachett once said that strong beliefs can win the hearts of strong people and make them stronger. This makes me think deeply",
    "Charles Scarborough once said that one can succeed in almost anything he has infinite enthusiasm for. This makes me think deeply",
    "Beethoven once said that one of the great advantages of an excellent person is that he is not forgiving in the adverse and difficult encounters. This makes me think deeply",
    "Shakespeare once said that if you try boldly, you can always succeed in things that are hopeless. This makes me think deeply",
    "Carnegie once said that if we have accepted the worst, there will be nothing to lose. This makes me think deeply",
    "Germany once said that you can only know yourself in the middle of a crowd. This makes me think deeply",
    "Smiles once said that books introduce us to the most beautiful society, and make us know the great wise men of all ages. This makes me think deeply",
    "Feng Xuefeng once said that when a person uses work to welcome the light, the light will soon shine on him. This makes me think deeply",
    "Jig Jinkla once said that if you can dream, you can achieve it. This makes me think deeply",
]

export const backWordsEN = [
    "This makes me think deeply. ",
    "With this sentence, we have to examine this issue more carefully: ",
    "This inspired me, ",
    "I hope you can also appreciate this sentence. ",
    "Although this sentence is very short, it makes me think about it. ",
]

export const preWordsEN = [
    "said before",
    "Said this accidentally",
]